-- Created On: 2024-09-29 05:45:01
-- Migration: clever-ramanujan
-- Created On: 2024-09-29 05:45:01
--
-- DO NOT EDIT THIS FILE AFTER COMMIT
-- CREATE A NEW MIGRATION INSTEAD
--

DROP TABLE IF EXISTS migrations;