-- Migration: clever-ramanujan
-- Created On: 2024-09-29 05:45:01
--
-- DO NOT EDIT THIS FILE AFTER COMMIT
-- CREATE A NEW MIGRATION INSTEAD
--

-- Table for tracking applied migrations
CREATE TABLE IF NOT EXISTS migrations (
    timestamp BIGINT UNSIGNED NOT NULL PRIMARY KEY COMMENT 'Unix timestamp of migration creation',
    name VARCHAR(255) NOT NULL UNIQUE COMMENT 'Migration name (e.g., adj-lastname)',
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=PENDING, 1=APPLIED, 2=FAILED',
    applied_at TIMESTAMP NULL COMMENT 'Timestamp when migration was applied',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
