-- Schema Overlay: cheeky-happy-ritchie (1727588702)
-- Created On: 2024-09-29 05:45:02
--
-- DO NOT EDIT THIS FILE AFTER IT HAS BEEN COMMITTED
-- CREATE A NEW SCHEMA OVERLAY `migrator.py create` INSTEAD
--

DROP TABLE IF EXISTS metadata;
