-- Schema Overlay: cheeky-happy-ritchie (1727588702)
-- Created On: 2024-09-29 05:45:02
--
-- DO NOT EDIT THIS FILE AFTER IT HAS BEEN COMMITTED
-- CREATE A NEW SCHEMA OVERLAY `migrator.py create` INSTEAD
--

-- The `metadata` table is used to store information about the database status, such as migration version, etc.
CREATE TABLE IF NOT EXISTS metadata (
	`id` BIGINT(12) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`key` VARCHAR(20) NOT NULL,
	`value` TEXT,
	`date_updated` BIGINT(12) UNSIGNED NOT NULL
);

-- Insert the `migration_data` key into the metadata K/V pair.
INSERT INTO metadata (`id`, `key`, `value`, `date_updated`) VALUES (NULL, "migration_data", '{"version":0}', UNIX_TIMESTAMP());
