-- Migration: dreamy-bohr
-- Created On: 2024-09-29 05:45:02
--
-- DO NOT EDIT THIS FILE AFTER COMMIT
-- CREATE A NEW MIGRATION INSTEAD
--

DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS user_notes;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS user_reputation_logs;
DROP TABLE IF EXISTS appeals;
DROP TABLE IF EXISTS moderation_actions;
DROP TABLE IF EXISTS oauth_sessions;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS user_warnings;
DROP TABLE IF EXISTS user_bans;
DROP TABLE IF EXISTS post_moderation_categories;
DROP TABLE IF EXISTS post_embeddings;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS community_members;
DROP TABLE IF EXISTS moderation_categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS communities;