-- Schema Overlay: awake-amazing-lichterman (1727588703)
-- Created On: 2024-09-29 05:45:02
--
-- DO NOT EDIT THIS FILE AFTER IT HAS BEEN COMMITTED
-- CREATE A NEW SCHEMA OVERLAY `migrator.py create` INSTEAD
--

DROP TABLE logs;
DROP TABLE user_violations;
DROP TABLE user_deltas;
DROP TABLE users;
DROP TABLE posts;
DROP TABLE post_comments;

